import { useEffect, useState } from 'react';

type Props = {
  /**
   * Image basename in `public/img/` (without width / extension).
   * Responsive variants are generated by scripts/optimize-images.mjs at
   * 160, 320, and 480 widths × avif/webp/jpg.
   */
  basename: string;
  alt: string;
  // CSS object-position value used to align the face inside the circular crop.
  // The default targets the eyes/glasses for /profile.
  focal?: string;
};

// Widths must match the ones produced by scripts/optimize-images.mjs.
const WIDTHS = [160, 320, 480] as const;

function srcset(basename: string, ext: 'avif' | 'webp' | 'jpg') {
  return WIDTHS.map((w) => `/img/${basename}-${w}.${ext} ${w}w`).join(', ');
}

// Soft fade-in on mount, mirroring the original site's hero entrance.
export default function Portrait({ basename, alt, focal = '50% 28%' }: Props) {
  const [visible, setVisible] = useState(false);
  useEffect(() => {
    const t = window.setTimeout(() => setVisible(true), 60);
    return () => window.clearTimeout(t);
  }, []);

  // sizes: 128 CSS px (h-32) on small screens, 160 CSS px (sm:h-40) above.
  const sizes = '(min-width: 640px) 160px, 128px';

  return (
    <div
      className={`
        relative
        h-32 w-32
        sm:h-40 sm:w-40
        rounded-full
        overflow-hidden
        ring-1 ring-white/20
        shadow-2xl
        transition-opacity duration-[1200ms] ease-out
        ${visible ? 'opacity-100' : 'opacity-0'}
      `}
    >
      <picture>
        <source type="image/avif" srcSet={srcset(basename, 'avif')} sizes={sizes} />
        <source type="image/webp" srcSet={srcset(basename, 'webp')} sizes={sizes} />
        <img
          src={`/img/${basename}-320.jpg`}
          srcSet={srcset(basename, 'jpg')}
          sizes={sizes}
          alt={alt}
          width={320}
          height={320}
          loading="eager"
          decoding="async"
          className="h-full w-full object-cover"
          style={{ objectPosition: focal }}
        />
      </picture>
    </div>
  );
}
